# Generated by Django 4.1.1 on 2022-10-02 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyearnings',
            name='usuario',
            field=models.ForeignKey(default=users.models.CustomUser, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
