# Generated by Django 4.1.1 on 2022-10-02 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0002_alter_monthlyearnings_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyearnings',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
