# Generated by Django 4.1.1 on 2022-10-03 02:24

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0007_alter_gain_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gain',
            name='usuario',
            field=models.CharField(default=users.models.CustomUser, editable=False, max_length=300),
        ),
    ]
