# Generated by Django 4.1.1 on 2022-10-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0013_alter_gain_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyEarnings',
        ),
    ]
