# Generated by Django 4.1.1 on 2022-10-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0015_alter_gain_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gain',
            name='usuario',
        ),
    ]
