# Generated by Django 4.1.1 on 2022-10-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0017_gain_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gain',
            name='author',
        ),
    ]
