# Generated by Django 4.1.1 on 2022-10-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0020_remove_gain_author_gain_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gain',
            name='data',
            field=models.DateTimeField(verbose_name='%d-%m-%y'),
        ),
    ]
