# Generated by Django 4.1.1 on 2022-10-04 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0021_alter_gain_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gain',
            name='data',
        ),
        migrations.AddField(
            model_name='gain',
            name='dia',
            field=models.IntegerField(default=None, verbose_name='Dia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gain',
            name='mes',
            field=models.IntegerField(default=None, verbose_name='Mês'),
            preserve_default=False,
        ),
    ]
