# Generated by Django 4.1.1 on 2022-10-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0024_lose'),
    ]

    operations = [
        migrations.AddField(
            model_name='lose',
            name='para',
            field=models.CharField(default=None, max_length=300, verbose_name='Destinatário'),
            preserve_default=False,
        ),
    ]
