# Generated by Django 4.1.1 on 2022-10-06 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('graphics', '0025_lose_para'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lose',
            name='para',
        ),
        migrations.AddField(
            model_name='lose',
            name='credor',
            field=models.CharField(default=None, max_length=300, verbose_name='Credor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Financa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('credor', models.CharField(max_length=300, verbose_name='Função')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
