# Generated by Django 4.1.1 on 2022-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0026_remove_lose_para_lose_credor_financa'),
    ]

    operations = [
        migrations.AddField(
            model_name='financa',
            name='descricao',
            field=models.CharField(blank=True, max_length=400, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='financa',
            name='credor',
            field=models.CharField(max_length=300, verbose_name='Função do pagamento'),
        ),
    ]
