# Generated by Django 4.1.1 on 2022-10-02 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_monthlyearnings_gain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyearnings',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Gain',
        ),
        migrations.DeleteModel(
            name='MonthlyEarnings',
        ),
    ]
